resource_group_name = "rg-aks-prod2"
environment         = "prod"
vnet_name           = "my-vnet"
aks_cluster_name    = "aks-prod"
acr_name            = "acrprodassignmnet4"
key_vault_name      = "kv-prod-1234demo"
log_analytics_name  = "law-prod"
